### ISSUE TITLE
Facing CORS issues while working with AWS Chime messaging SDK

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1355]
I took the example from :
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/demo/chat/src/api/ChimeAPI.js

I am getting below error.
```
Access to XMLHttpRequest at 'https://chime.us-east-1.amazonaws.com/accounts/123456781234/users?operation=create' from origin 'http://localhost:3050' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
xhr.js:81 POST https://chime.us-east-1.amazonaws.com/accounts/123456781234/users?operation=create net::ERR_FAILED
```

here is my code:

```
import appConfig from '../../config/aws.config';
// eslint-disable-next-line no-unused-vars
const AWS = require('aws-sdk');
const Chime = require('aws-sdk/clients/chime');

AWS.config.update({
  accessKeyId: appConfig.AWS_ACCESS_KEY_ID,
  secretAccessKey: appConfig.AWS_SECRET_ACCESS_KEY
});

// Setup Chime Client
async function chimeClient() {
  const chime = new Chime({
    region: 'us-east-1',
    accessKeyId: appConfig.AWS_ACCESS_KEY_ID,
    secretAccessKey: appConfig.AWS_SECRET_ACCESS_KEY
  });
  return chime;
}

// create chime user
async function createUser(user) {
  var params = {
    AccountId: appConfig.AWS_ACCOUNT_ID, /* required */
    Email: user.email,
    UserType: "PrivateUser",
    Username: user.email
  };
  var chime = await chimeClient();
  return new Promise((resolve, reject) => {
    chime.createUser(params, function(err, data) {
      if (err) {
        console.log(err, err.stack);
        reject(err);
      } // an error occurred
      else {
        console.log(data);
        resolve(data);
      } // successful response
    });
  });
}
```

I don't understand how can I pass the  **x-amz-chime-bearer request header** from the above function of my reactjs client app.

**Comment by dpwspoon** [comment]
Sorry for the confusion.  Currently the APIs for the chime application and the chime messaging SDK are in the same documentation and package.  We are working on separating them.  The API you are looking for is create-app-instance-user.  The Messaging SDK apis generally have "channel" or "app-instance" in the name.

**Comment by abhimanusharma** [comment]
@dpwspoon  I understand that, but I want to know what is **AppInstanceUserId**?
Is this the email id or uuid of new user that I want to create for messaging?
I want an anonymous user to create an channel and send message to another anonymous user. Their email id is not saving on cognito or anywhere just saving them temporarily in db as records.

**Comment by abhimanusharma** [comment]
@dpwspoon Ok thanks for pointing me in the right direction. So now I am able to create an app instance user and got the userArn but that user can't do anything.
When I tried to call the createChannel api using that app instance user's ARN then I am getting below error.

```
createChannel called
Unauthorized: An invalid app instance user ARN was supplied for the x-amz-chime-bearer HTTP header.
    at Object.extractError (/var/www/html/project_dev/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/var/www/html/project_dev/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/www/html/project_dev/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/www/html/project_dev/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/www/html/project_dev/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/www/html/project_dev/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/www/html/project_dev/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/www/html/project_dev/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/www/html/project_dev/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/www/html/project_dev/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/var/www/html/project_dev/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/var/www/html/project_dev/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/www/html/project_dev/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/www/html/project_dev/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/www/html/project_dev/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/www/html/project_dev/node_modules/aws-sdk/lib/state_machine.js:26:10 {
  code: 'Unauthorized',
  time: 2021-06-10T13:20:29.477Z,
  requestId: '3ffc6414-1c3a-480d-be3d-2057e59f681b',
  statusCode: 401,
  retryable: false,
  retryDelay: 70.14565292409173
}

```

I am passing the exact same userArn as I've received from the previous request but still getting errors.

**Comment by abhimanusharma** [comment]
@dpwspoon I was stuck when using MessegingSessionConfiguration but as per your suggestion I tried to use AWS STS but I am getting 403 unauthorized error.
```
AccessDenied: User: arn:aws:iam::1234567891234:user/My_secret_User is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1234567891234:role/anonymousAttendee
```

I have added all the policies for the above user for STS.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "sts:*",
            "Resource": "*"
        }
    ]
}
```

#1355 
Now I tried to use CreateAppInstanceUser to generate the userArn. Then use that userArn to create a messaging channel membership but getting **422 Unprocessable Entity**

```
{
    "statusCode": 422,
    "success": false,
    "message": "An invalid app instance user ARN was supplied for the x-amz-chime-bearer HTTP header.",
    "errors": []
}
```

**My payload:**
```
{
    "channelArn": "arn:aws:chime:us-east-1:1234567891234:app-instance/0937ae10-fb1f-49a9-8423-305b945623f3/channel/986e0758adaf7c5ccbafeab9a1fa71a2228391dfb0eb42a457dac7412629e35d",
    "memberArn": "arn:aws:chime:us-east-1:1234567891234:app-instance/0937ae10-fb1f-49a9-8423-305b945623f3/user/sdfs@fdsf.ccc",
    "userId": "sdfs1@fdsf.ccc"
}
```

As there are no members in the channel yet (maybe except the channel creator himself). So, why this is giving me invalid app instance user in the header when I am using the same userArn to create the channel (**createChannel**). I am getting same error for **sendChannelMessage** but I guess that won't work until there are more than 1 user in that channel?

I don't really get why there is no single article/tutorial or proper documentation to use AWS Chime Messaging SDK.
