### ISSUE TITLE
createMediaCapturePipeline API gives "ResourceLimitExceeded" error

### ISSUE THREAD

**Issue by aag-sl** [aws/amazon-chime-sdk-js#1552]
After successful deployment, trying to run the sample app provided in **/demos/browser**. Getting the following error in Cloudwatch,
```
ERROR   Invoke Error    {
    "errorType": "ResourceLimitExceeded",
    "errorMessage": "Cannot create new media capture pipeline for source type 'ChimeSdkMeeting' and source arn 'arn:aws:chime::*********:meeting:1be4e26f-0204-41dd-9e9a-1dc903fc0706'. Limit reached",
    "code": "ResourceLimitExceeded",
    "message": "Cannot create new media capture pipeline for source type 'ChimeSdkMeeting' and source arn 'arn:aws:chime::*********:meeting:1be4e26f-0204-41dd-9e9a-1dc903fc0706'. Limit reached",
    "time": "*********",
    "requestId": "*********",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 57.02889191183074,
    "stack": [
        "ResourceLimitExceeded: Cannot create new media capture pipeline for source type 'ChimeSdkMeeting' and source arn 'arn:aws:chime::*********:meeting:1be4e26f-0204-41dd-9e9a-1dc903fc0706'. Limit reached",
        "    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12)"
    ]
}
```
Could not find any options to increase the service quota limit (if any).

**Comment by sinanliuAmazon** [comment]
Hi @aag-sl , media capture pipeline has meeting level limit, only one media capture pipeline is allowed in one ChimeSdkMeeting. I checked the logs and seems there's 3 CreateMediaCapturePipeline API calls for meetingId: 1be4e26f-0204-41dd-9e9a-1dc903fc0706, the first one created a media capture pipeline already, so the following 2 failed with limit exceed error message.

**Comment by aag13** [comment]
Hi @sinanliuAmazon , thanks a lot for your response. Much appreciated!

**Comment by aag-sl** [comment]
Hi @sinanliuAmazon , thanks a lot for your response. Much appreciated!
