### ISSUE TITLE
AWS authorization failed when calling chime.startChimeTranscription

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#1562]
### What are you trying to do?
I'm trying to start transcription on a chime meeting. Got this error. Am I missing something?

Already added this role:
AWSServiceRoleForAmazonChimeTranscription

aws-sdk version nodejs: 
2.979.0

TranscriptionConfiguration:
{ EngineTranscribeSettings: { LanguageCode: 'en-US' } }

Error message:
Forbidden: AWS authorization failed
    at Object.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:52:27)
    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'Forbidden',
  time: 2021-08-31T16:30:22.608Z,
  requestId: '7faae5c1-8ffe-4ddd-b5cd-05c5e9fe361f',
  statusCode: 403,
  retryable: false,
  retryDelay: 64.29107172963042
}

### How can the documentation be improved to help your use case?
Include a section on what to check if we encounter certain errors.

### What documentation have you looked at so far?
Readme and  https://docs.aws.amazon.com/chime/latest/dg/configure-transcribe.html

**Comment by dnnejo** [comment]
In the StartMeetingTranscription API, you have the option of specifying the region.  If you do not, it uses the same region as the meeting, and if Amazon Transcribe is not available in that region, you will receive an error.  Use "region = 'auto'" to have Amazon Chime use Amazon Transcribe in a nearby region if it is not available in the meeting region.
https://docs.aws.amazon.com/chime/latest/APIReference/API_StartMeetingTranscription.html

If you are hosting a meeting in an "opt in" region (eu-south-1, af-south-1), then you must "enable" those regions for your AWS account for Amazon Chime to invoke Amazon Transcribe from that region (regardless of the region of Amazon Transcribe)
https://docs.aws.amazon.com/chime/latest/dg/transcription-options.html#choose-region

Do let us know if this resolves your issue.

**Comment by paul365** [comment]
@dnnejo thanks! I also used your suggestion. I resolved it by granting full access to chime. might have missed these
              - 'chime:StartMeetingTranscription'
              - 'chime:StopMeetingTranscription'
Might be helpful if the documentation also has info the above is also needed aside from adding the service role.
