### ISSUE TITLE
No DNS resolution to chime.<region>.amazonaws.com

### ISSUE THREAD

**Issue by ngines** [aws/amazon-chime-sdk-js#283]
**Describe the bug**
When doing a quick test using the JS SDK, we got the following error:

Error: getaddrinfo ENOTFOUND chime.us-east-1.amazonaws.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)

We checked the DNS resolution for chime.<region>.amazonaws.com for multiple regions and none worked. The construct seems valid as for instance, dynamodb.us-east-1.amazonaws.com resolves correctly. Any suggestions?

**Platform**
 - OS: Mac OSX 10.13.6
 - Browser: Chrome
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:  2.658.0

**Comment by vidya-mohan** [comment]
Hi ngines@ thanks for the interest in the SDK. Currently we support a global endpoint of service.chime.aws.amazon.com only which you can use to unblock yourself. We will track this issue till this new endpoint is supported

**Comment by aburnson** [comment]
If your server application is using the AWS SDK for JavaScript, then you would do the following to construct the Chime object:

```
const chime = new AWS.Chime({ region: 'us-east-1' });
chime.endpoint = new AWS.Endpoint('https://service.chime.aws.amazon.com/console');
```

Currently `us-east-1` is the only region the Amazon Chime API is defined in. However, when you call CreateMeeting, you can select the region the meeting is hosted in with the [MediaRegion](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html#chime-CreateMeeting-request-MediaRegion) parameter.

**Comment by ngines** [comment]
Thank you @vidya-mohan and @aburnson, this helps. We are able to progress past this issue; now facing authorization issues.

**Comment by aburnson** [comment]
> now facing authorization issues

Could you share the error you are receiving? Ensure that you are using credentials with an IAM role that has the [AmazonChimeSDK policy](https://console.aws.amazon.com/iam/home?#/policies/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2FAmazonChimeSDK) attached.

**Comment by ngines** [comment]
Thanks Andrew. Here is the error I got, even though I have attached the AmazonChimeSDK policy to my IAM user. Thx

`utils/seeds.js -> dist/utils/seeds.js
utils/transform/date.js -> dist/utils/transform/date.js
utils/transform/index.js -> dist/utils/transform/index.js
utils/transform/string.js -> dist/utils/transform/string.js
ForbiddenException: AWS authorization failed
    at Object.extractError (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at Request.emit (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
    at callNextListener (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at IncomingMessage.onEnd (/Users/manny/Documents/Empresa/chime/EmpresaSOS-Models/node_modules/aws-sdk/lib/event_listeners.js:307:13)
    at IncomingMessage.emit (events.js:333:22)`

**Comment by aburnson** [comment]
> ForbiddenException: AWS authorization failed

Could you share more information about the request that caused this error?

- Time of request (UTC)
- The code used to create the `AWS.Chime` object and the calls made on that object

**Comment by ngines** [comment]
> > ForbiddenException: AWS authorization failed
> 
> Could you share more information about the request that caused this error?
> 
> * Time of request (UTC)


Wed Apr 22 23:57:15 2020 UTC


> * The code used to create the `AWS.Chime` object and the calls made on that object

```
export class chime {

    createMeeting(params) {
        return new Promise((resolve, reject) => {
          const chime = new AWS.Chime({ region: 'us-east-1' });
          chime.endpoint = new AWS.Endpoint('https://service.chime.aws.amazon.com/console');

          chime.createMeeting(params, (err, data) => {
              if (err) reject(err.stack); // an error occurred
              else     resolve(data);           // successful response
            })
        });
    }
}

```

```
export class chimeServiceTest {
    static run(){
        const chimeTest = new chime();
        const tokenid = uuid.v4();
        const params = {
            ClientRequestToken: tokenid, /* required */
            MediaRegion: 'us-east-1',
        };
        chimeTest.createMeeting(params).then((response) => {
            console.log(response);
        }).catch((error) => {
            console.log(error);
        });
    }
}

chimeServiceTest.run();
```

**Comment by aburnson** [comment]
Thanks. The above code is fine in terms of setting up the `AWS.Chime` object and making the `createMeeting` call. Since this is an authorization failure, it sounds like the `chime` object may not have the credentials for the role with the AmazonChimeSDK policy.

**Comment by ltrung** [comment]
@ngines Do you still have issue with this?

**Comment by vidya-mohan** [comment]
This issue has been fixed. @ngines could you retry the request for 'dig chime.us-east-1.amazonaws.com' ?
