### ISSUE TITLE
Error: Cannot select audio output device. This browser does not support setSinkId. [SDK Version: ^3.21.1]

### ISSUE THREAD

**Issue by KimberleyChee** [aws/amazon-chime-sdk-js#2941]
### What happened and what did you expect to happen?

**What happened:**
- Meeting started with audio input and video input, but not audio output
- Unable to hear speaker
- Error: 
![image](https://github.com/user-attachments/assets/ea870a87-3f01-4678-9f2f-628ee669e81b)

**Expected Behaviour:**
- Meeting started with audio input, video input, and audio output
- Able to hear speaker

**Environment:**
Device: Samsung Galaxy Note 9
OS: Android 10
Browser: Android System WebView (chromium webview 127)
Version: 127.0.6533
Framework: Cordova 12.0.0 (cordova-lib@12.0.1) Android 13.0.0

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

`if (chime.browserBehaviour.supportsSetSinkId()) {
            try {
                chime.chosenSpeaker = mediaDevices.speakers[0];
                await meetingSession.audioVideo.chooseAudioOutput(chime.chosenSpeaker.deviceId);
            } catch (e) {
                this.log('failed to chooseAudioOutputDevice', e);
            }
        }`
        
`// Bind audio stream
        const audioElement = document.getElementById('videocall-local-audio');
        try {
            await meetingSession.audioVideo.bindAudioElement(audioElement);
        } catch (e) {
            this.log('failed to bindAudioElement', e);
        }`

### Amazon Chime SDK for JavaScript version

^3.21.1

### What browsers are you seeing the problem on?

Android System WebView (chromium webview 127)

### Browser version

127.0.6533

### Browser console logs

amazon-chime-sdk.min.js:1 2024-08-21T10:03:11.083Z [INFO] ChimeMeetingLogs - DefaultDeviceController video dimension 960 x 540
amazon-chime-sdk.min.js:1 2024-08-21T10:03:11.088Z [INFO] ChimeMeetingLogs - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"displaySurface":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"suppressLocalAudioPlayback":true,"tilt":true,"torch":true,"voiceIsolation":true,"whiteBalanceMode":true,"width":true,"zoom":true}
2024-08-21T10:03:11.173Z [INFO] ChimeMeetingLogs - DefaultDeviceController video dimension 960 x 540
amazon-chime-sdk.min.js:1 2024-08-21T10:03:11.174Z [INFO] ChimeMeetingLogs - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"displaySurface":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"suppressLocalAudioPlayback":true,"tilt":true,"torch":true,"voiceIsolation":true,"whiteBalanceMode":true,"width":true,"zoom":true}
2024-08-21T10:03:12.385Z [INFO] ChimeMeetingLogs - browser is chromium-webview 127 (127.0.6533)
amazon-chime-sdk.min.js:1 2024-08-21T10:03:12.386Z [INFO] ChimeMeetingLogs - Event ingestion URL is present in the configuration
amazon-chime-sdk.min.js:1 2024-08-21T10:03:12.391Z [INFO] ChimeMeetingLogs - Event reporting started
amazon-chime-sdk.min.js:1 2024-08-21T10:03:12.393Z [INFO] ChimeMeetingLogs - MeetingFeatures: {"videoMaxResolution":{"videoWidth":1280,"videoHeight":720,"videoFrameRate":30},"contentMaxResolution":{"videoWidth":1920,"videoHeight":1080,"videoFrameRate":30}}
amazon-chime-sdk.min.js:1 2024-08-21T10:03:12.394Z [INFO] ChimeMeetingLogs - adding meeting observer
2024-08-21T10:03:13.982Z [INFO] ChimeMeetingLogs - attempting to trigger media device labels since they are hidden
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.134Z [INFO] ChimeMeetingLogs - API/DefaultDeviceController/listAudioInputDevices false -> [{"deviceId":"default","kind":"audioinput","label":"","groupId":"70e8555fe59caf69dd3bb049e15ac8bfaec13059a58456af540fd24b630df1e8"},{"deviceId":"e4c1b9b75d30a9da189ced76c5e0ef2c7b0e22f5de6308290c9e89637c13b4ee","kind":"audioinput","label":"Speakerphone","groupId":"965069e8ea8b66e6508f28e0164406d797ca07cbad7f4ef8070c2f09f9362a47"},{"deviceId":"a5cf8444e0b951938c9ad171a5fbda9861050a2d2edf9edfc679ee7dedc0a6a8","kind":"audioinput","label":"Wired headset","groupId":"5235643bce94bdc7c5e1b8ac6248939f1a7785afd951a65796ffb803b97f1baa"}]
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.135Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/904e5d93-821d-4a5a-8e75-0abd95683049/ad912943-7541-b306-702a-b40ebc765483/listAudioInputDevices false -> [{"deviceId":"default","kind":"audioinput","label":"","groupId":"70e8555fe59caf69dd3bb049e15ac8bfaec13059a58456af540fd24b630df1e8"},{"deviceId":"e4c1b9b75d30a9da189ced76c5e0ef2c7b0e22f5de6308290c9e89637c13b4ee","kind":"audioinput","label":"Speakerphone","groupId":"965069e8ea8b66e6508f28e0164406d797ca07cbad7f4ef8070c2f09f9362a47"},{"deviceId":"a5cf8444e0b951938c9ad171a5fbda9861050a2d2edf9edfc679ee7dedc0a6a8","kind":"audioinput","label":"Wired headset","groupId":"5235643bce94bdc7c5e1b8ac6248939f1a7785afd951a65796ffb803b97f1baa"}]
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.176Z [INFO] ChimeMeetingLogs - attempting to trigger media device labels since they are hidden
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.330Z [INFO] ChimeMeetingLogs - API/DefaultDeviceController/listAudioOutputDevices false -> [{"deviceId":"default","kind":"audiooutput","label":"","groupId":"default"}]
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.330Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/904e5d93-821d-4a5a-8e75-0abd95683049/ad912943-7541-b306-702a-b40ebc765483/listAudioOutputDevices false -> [{"deviceId":"default","kind":"audiooutput","label":"","groupId":"default"}]
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.376Z [INFO] ChimeMeetingLogs - attempting to trigger media device labels since they are hidden
global.js:1626 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
dragElement @ global.js:1626
(anonymous) @ global.js:1513
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.765Z [INFO] ChimeMeetingLogs - API/DefaultDeviceController/listVideoInputDevices false -> [{"deviceId":"a5cf8444e0b951938c9ad171a5fbda9861050a2d2edf9edfc679ee7dedc0a6a8","kind":"videoinput","label":"camera2 1, facing front","groupId":"15841e2872e510cdeaab8ead77be3f3987f0c26ea3ced7e27ffa502a1507e111"},{"deviceId":"50784f722543f29ea19ec15f5875b1e309d60a70be10ec0ec55c356896044f1d","kind":"videoinput","label":"camera2 2, facing front","groupId":"ca485a66f7ec3a7164cb7666042eec8035a626c6adcdb38434aab34c86bc8c79"},{"deviceId":"e4c1b9b75d30a9da189ced76c5e0ef2c7b0e22f5de6308290c9e89637c13b4ee","kind":"videoinput","label":"camera2 0, facing back","groupId":"78957461c608e81f3f7abcb23b25a8fd0d564b9f1c8777cb6f86fc7a975a4599"}]
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.766Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/904e5d93-821d-4a5a-8e75-0abd95683049/ad912943-7541-b306-702a-b40ebc765483/listVideoInputDevices false -> [{"deviceId":"a5cf8444e0b951938c9ad171a5fbda9861050a2d2edf9edfc679ee7dedc0a6a8","kind":"videoinput","label":"camera2 1, facing front","groupId":"15841e2872e510cdeaab8ead77be3f3987f0c26ea3ced7e27ffa502a1507e111"},{"deviceId":"50784f722543f29ea19ec15f5875b1e309d60a70be10ec0ec55c356896044f1d","kind":"videoinput","label":"camera2 2, facing front","groupId":"ca485a66f7ec3a7164cb7666042eec8035a626c6adcdb38434aab34c86bc8c79"},{"deviceId":"e4c1b9b75d30a9da189ced76c5e0ef2c7b0e22f5de6308290c9e89637c13b4ee","kind":"videoinput","label":"camera2 0, facing back","groupId":"78957461c608e81f3f7abcb23b25a8fd0d564b9f1c8777cb6f86fc7a975a4599"}]
login.js:182 (3) [InputDeviceInfo, InputDeviceInfo, InputDeviceInfo]
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.767Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/904e5d93-821d-4a5a-8e75-0abd95683049/ad912943-7541-b306-702a-b40ebc765483/startAudioInput "default"
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.768Z [INFO] ChimeMeetingLogs - Choosing intrinsic audio input device default
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.769Z [INFO] ChimeMeetingLogs - requesting new audio device with constraint {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.825Z [INFO] ChimeMeetingLogs - got audio device for constraints {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.826Z [INFO] ChimeMeetingLogs - Starting devicechange listener.
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.827Z [INFO] ChimeMeetingLogs - API/DefaultDeviceController/startAudioInputDevice "default" -> "success"
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.829Z [INFO] ChimeMeetingLogs - API/DefaultDeviceController/chooseAudioOutput "default" -> null
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.829Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/904e5d93-821d-4a5a-8e75-0abd95683049/ad912943-7541-b306-702a-b40ebc765483/chooseAudioOutput "default"
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.830Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/904e5d93-821d-4a5a-8e75-0abd95683049/ad912943-7541-b306-702a-b40ebc765483/startVideoInput "a5cf8444e0b951938c9ad171a5fbda9861050a2d2edf9edfc679ee7dedc0a6a8"
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.830Z [INFO] ChimeMeetingLogs - requesting new video device with constraint {"video":{"deviceId":{"exact":"a5cf8444e0b951938c9ad171a5fbda9861050a2d2edf9edfc679ee7dedc0a6a8"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15}}}
amazon-chime-sdk.min.js:1 2024-08-21T10:03:14.836Z [INFO] ChimeMeetingLogs - Receive an audio output change event
amazon-chime-sdk.min.js:1 Uncaught (in promise) Error: Cannot select audio output device. This browser does not support setSinkId.
    at DefaultAudioMixController.<anonymous> (amazon-chime-sdk.min.js:1:413578)
    at Generator.next (<anonymous>)
    at amazon-chime-sdk.min.js:1:412293
    at new Promise (<anonymous>)
    at __awaiter$L (amazon-chime-sdk.min.js:1:412027)
    at DefaultAudioMixController.bindAudioDevice (amazon-chime-sdk.min.js:1:413480)
    at DefaultAudioMixController.<anonymous> (amazon-chime-sdk.min.js:1:415266)
    at Generator.next (<anonymous>)
    at amazon-chime-sdk.min.js:1:412293
    at new Promise (<anonymous>)

**Comment by KimberleyChee** [comment]
Fixed: the solution was to add `<uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" /> ` to the config.xml
