### ISSUE TITLE
Serverless Demo Issue (Ubuntu)

### ISSUE THREAD

**Issue by cmpeguerog** [aws/amazon-chime-sdk-js#545]
Issue when deploying serverless demo on Ubuntu.

```
14 verbose stack Error: amazon-chime-sdk-js-serverless-demos@0.1.0 deploy: `node ./deploy.js "-r" "us-east-1" "-b" "chime-serverless-demo-bucket" "-s" "chime-severless-demo-stack" "-a" "meeting"`
14 verbose stack Exit status 243
14 verbose stack     at EventEmitter.<anonymous> (/snap/node/2799/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:315:20)
14 verbose stack     at ChildProcess.<anonymous> (/snap/node/2799/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:315:20)
14 verbose stack     at maybeClose (internal/child_process.js:1051:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
......
19 verbose node v14.4.0
20 verbose npm  v6.14.5
21 error code ELIFECYCLE
22 error errno 243
```
**OS**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco
```

**Comment by RidipDe** [comment]
Can you please confirm you have the [prerequisites](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless#prerequisites) installed and setup

**Comment by cmpeguerog** [comment]
```
AWS CLI
aws-cli/2.0.30 Python/3.7.3 Linux/5.0.0-38-generic botocore/2.0.0dev34

SAM CLI
SAM CLI, version 0.53.0

Node
v14.4.0

NPM
v6.14.5
```

**Comment by simmkyu** [comment]
I just tried deploying the severless demo app in Ubuntu 18. It suceeded without any issue.

```
ubuntu@:~/amazon-chime-sdk-js/demos/serverless$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

I tried both AWS CLI version 1 and AWS CLI version 2. Both versions worked for me.

```
ubuntu@:~/amazon-chime-sdk-js/demos/serverless$ aws --version
aws-cli/1.18.99 Python/2.7.17 Linux/5.3.0-1023-aws botocore/1.17.22
aws-cli/2.0.31 Python/3.7.3 Linux/5.3.0-1023-aws botocore/2.0.0dev35

ubuntu@:~/amazon-chime-sdk-js/demos/serverless$ sam --version
SAM CLI, version 0.53.0

ubuntu@:~/amazon-chime-sdk-js/demos/serverless$ node -v
v14.5.0

ubuntu@:~/amazon-chime-sdk-js/demos/serverless$ npm -v
6.14.5
```

Full logs for reference (Don't use the same bucket name in this log)
```
ubuntu@:~/amazon-chime-sdk-js/demos/serverless$ npm run deploy -- -r us-east-1 -b github-issue-545 -s github-issue-545 -a meeting

> amazon-chime-sdk-js-serverless-demos@0.1.0 deploy /home/ubuntu/amazon-chime-sdk-js/demos/serverless
> node ./deploy.js "-r" "us-east-1" "-b" "github-issue-545" "-s" "github-issue-545" "-a" "meeting"

aws-cli/2.0.31 Python/3.7.3 Linux/5.3.0-1023-aws botocore/2.0.0dev35

SAM CLI, version 0.53.0

removed 12 packages and audited 20 packages in 0.5s
found 0 vulnerabilities


Verifying application meeting
Verifying application meetingV2
Using region us-east-1, bucket github-issue-545, stack github-issue-545
added 12 packages from 58 contributors and audited 808 packages in 3.588s
found 17 vulnerabilities (13 low, 1 moderate, 1 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

audited 1748 packages in 7.734s
found 5 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details


Successfully packaged artifacts and wrote output template to file build/packaged.yaml.
Execute the following command to deploy the packaged template
sam deploy --template-file /home/ubuntu/amazon-chime-sdk-js/demos/serverless/build/packaged.yaml --stack-name <YOUR STACK NAME>


Deploying serverless application

  Deploying with following values
  ===============================
  Stack name                 : github-issue-545
  Region                     : us-east-1
  Confirm changeset          : False
  Deployment s3 bucket       : None
  Capabilities               : ["CAPABILITY_IAM"]
  Parameter overrides        : {'UseEventBridge': 'false'}

Initiating deployment
=====================
ChimeSdkIndexLambda may not have authorization defined.
ChimeSdkIndexV2Lambda may not have authorization defined.
ChimeSdkJoinLambda may not have authorization defined.
ChimeSdkEndLambda may not have authorization defined.
ChimeSdkBrowserLogsLambda may not have authorization defined.

Waiting for changeset to be created..

CloudFormation stack changeset
------------------------------------------------------------------------------------------------
Operation                        LogicalResourceId                ResourceType                   
------------------------------------------------------------------------------------------------
* Modify                         ChimeSQSQueueLambda              AWS::Lambda::Function          
* Modify                         ChimeSdkBrowserLogsLambda        AWS::Lambda::Function          
* Modify                         ChimeSdkEndLambda                AWS::Lambda::Function          
* Modify                         ChimeSdkIndexLambda              AWS::Lambda::Function          
* Modify                         ChimeSdkIndexV2Lambda            AWS::Lambda::Function          
* Modify                         ChimeSdkJoinLambda               AWS::Lambda::Function          
* Modify                         ServerlessRestApi                AWS::ApiGateway::RestApi       
------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-east-1:...:changeSet/samcli-deploy1594943585/...


2020-07-16 23:53:15 - Waiting for stack create/update to complete

CloudFormation events from changeset
-------------------------------------------------------------------------------------------------
ResourceStatus           ResourceType             LogicalResourceId        ResourceStatusReason   
-------------------------------------------------------------------------------------------------
UPDATE_IN_PROGRESS       AWS::Lambda::Function    ChimeSdkJoinLambda       -                      
UPDATE_IN_PROGRESS       AWS::Lambda::Function    ChimeSdkIndexLambda      -                      
UPDATE_IN_PROGRESS       AWS::Lambda::Function    ChimeSdkBrowserLogsLam   -                      
                                                  bda                                             
UPDATE_IN_PROGRESS       AWS::Lambda::Function    ChimeSdkIndexV2Lambda    -                      
UPDATE_IN_PROGRESS       AWS::Lambda::Function    ChimeSdkEndLambda        -                      
UPDATE_IN_PROGRESS       AWS::Lambda::Function    ChimeSQSQueueLambda      -                      
UPDATE_COMPLETE          AWS::Lambda::Function    ChimeSdkBrowserLogsLam   -                      
                                                  bda                                             
UPDATE_COMPLETE          AWS::Lambda::Function    ChimeSdkIndexV2Lambda    -                      
UPDATE_COMPLETE          AWS::Lambda::Function    ChimeSdkEndLambda        -                      
UPDATE_COMPLETE          AWS::Lambda::Function    ChimeSQSQueueLambda      -                      
UPDATE_COMPLETE          AWS::Lambda::Function    ChimeSdkJoinLambda       -                      
UPDATE_COMPLETE          AWS::Lambda::Function    ChimeSdkIndexLambda      -                      
UPDATE_COMPLETE_CLEANU   AWS::CloudFormation::S   github-issue-545         -                      
P_IN_PROGRESS            tack                                                                     
UPDATE_COMPLETE          AWS::CloudFormation::S   github-issue-545         -                      
                         tack                                                                     
-------------------------------------------------------------------------------------------------

CloudFormation outputs from deployed stack
-------------------------------------------------------------------------------------------------
Outputs                                                                                         
-------------------------------------------------------------------------------------------------
Key                 ApiURL                                                                      
Description         API endpoint URL for Prod environment                                       
Value               ...
-------------------------------------------------------------------------------------------------

Successfully created/updated stack - github-issue-545 in us-east-1


Amazon Chime SDK Meeting Demo URL: 
...
```

**Comment by simmkyu** [comment]
These are other GitHub issues related to the `verbose stack Exit status 243` error. There seems to be a NPM permission error. Please try deploying again after running suggested solutions here:

- https://github.com/hexojs/hexo/issues/2505
- https://github.com/hexojs/hexo/issues/2591
- https://github.com/infinitered/ignite/issues/219

**Comment by simmkyu** [comment]
Please review the NPM permission errors in those links and reopen if you still see the issues.
