### ISSUE TITLE
An error occurred (SignatureDoesNotMatch) when calling the PutObject operation

### ISSUE THREAD

**Issue by CSLLCUser** [aws/amazon-chime-sdk-js#552]
Encounter the following exception when attempting to deploy the serverless demo

```
npm run deploy -- -r us-east-1 -b 4J67-Y102-AAB5-meeting-bucket -s my-meeting-stack -a meeting

> amazon-chime-sdk-js-serverless-demos@0.1.0 deploy /Users/figgus/Amazon/sdk/Javascript/amazon-chime-sdk-js-master/demos/serverless
> node ./deploy.js "-r" "us-east-1" "-b" "4J67-Y102-AAB5-meeting-bucket" "-s" "my-meeting-stack" "-a" "meeting"

aws-cli/2.0.26 Python/3.7.4 Darwin/19.5.0 botocore/2.0.0dev30

SAM CLI, version 0.53.0

audited 20 packages in 0.367s
found 0 vulnerabilities


Verifying application meeting
Verifying application meetingV2
Using region us-east-1, bucket 4J67-Y102-AAB5-meeting-bucket, stack my-meeting-stack
Creating S3 bucket 4J67-Y102-AAB5-meeting-bucket
added 12 packages from 58 contributors and audited 811 packages in 1.74s
found 17 vulnerabilities (13 low, 1 moderate, 1 high, 2 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

audited 1748 packages in 4.284s
found 5 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details


Command sam failed with exit code 1 signal null
Error: Unable to upload artifact src/ referenced by CodeUri parameter of ChimeSdkIndexLambda resource.
An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-chime-sdk-js-serverless-demos@0.1.0 deploy: `node ./deploy.js "-r" "us-east-1" "-b" "4J67-Y102-AAB5-meeting-bucket" "-s" "my-meeting-stack" "-a" "meeting"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the amazon-chime-sdk-js-serverless-demos@0.1.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/figgus/.npm/_logs/2020-07-14T20_49_13_061Z-debug.log




******************
From /Users/figgus/.npm/_logs/2020-07-14T16_43_17_668Z-debug.log



0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy',
1 verbose cli   '--',
1 verbose cli   '-r',
1 verbose cli   'us-east-1',
1 verbose cli   '-b',
1 verbose cli   '4J67-Y102-AAB5-meeting-bucket',
1 verbose cli   '-s',
1 verbose cli   'my-meeting-stack',
1 verbose cli   '-a',
1 verbose cli   'meeting'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle amazon-chime-sdk-js-serverless-demos@0.1.0~predeploy: amazon-chime-sdk-js-serverless-demos@0.1.0
6 info lifecycle amazon-chime-sdk-js-serverless-demos@0.1.0~deploy: amazon-chime-sdk-js-serverless-demos@0.1.0
7 verbose lifecycle amazon-chime-sdk-js-serverless-demos@0.1.0~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle amazon-chime-sdk-js-serverless-demos@0.1.0~deploy: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/figgus/Amazon/sdk/Javascript/amazon-chime-sdk-js-master/demos/serverless/node_modules/.bin:/Users/figgus/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS
9 verbose lifecycle amazon-chime-sdk-js-serverless-demos@0.1.0~deploy: CWD: /Users/figgus/Amazon/sdk/Javascript/amazon-chime-sdk-js-master/demos/serverless
10 silly lifecycle amazon-chime-sdk-js-serverless-demos@0.1.0~deploy: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'node ./deploy.js "-r" "us-east-1" "-b" "4J67-Y102-AAB5-meeting-bucket" "-s" "my-meeting-stack" "-a" "meeting"'
10 silly lifecycle ]
11 silly lifecycle amazon-chime-sdk-js-serverless-demos@0.1.0~deploy: Returned: code: 1  signal: null
12 info lifecycle amazon-chime-sdk-js-serverless-demos@0.1.0~deploy: Failed to exec deploy script
13 verbose stack Error: amazon-chime-sdk-js-serverless-demos@0.1.0 deploy: `node ./deploy.js "-r" "us-east-1" "-b" "4J67-Y102-AAB5-meeting-bucket" "-s" "my-meeting-stack" "-a" "meeting"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid amazon-chime-sdk-js-serverless-demos@0.1.0
15 verbose cwd /Users/figgus/Amazon/sdk/Javascript/amazon-chime-sdk-js-master/demos/serverless
16 verbose Darwin 19.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "deploy" "--" "-r" "us-east-1" "-b" "4J67-Y102-AAB5-meeting-bucket" "-s" "my-meeting-stack" "-a" "meeting"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error amazon-chime-sdk-js-serverless-demos@0.1.0 deploy: `node ./deploy.js "-r" "us-east-1" "-b" "4J67-Y102-AAB5-meeting-bucket" "-s" "my-meeting-stack" "-a" "meeting"`
22 error Exit status 1
23 error Failed at the amazon-chime-sdk-js-serverless-demos@0.1.0 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Platform**
 - OS: Mac OS Catalina 10.15.5
 - Browser: N/A
 - Browser Version: N/A
 - Amazon Chime SDK GitHub Commit: fe48254
 - npm version : 6.14.5
 - node version: 14.4.0

**Comment by CSLLCUser** [comment]
Solved.  The problem arises because the deployment depends upon environment variables.  If the environment variables are set to a different profile than the one the deployment is launched with, this error is encountered.

**Comment by simmkyu** [comment]
Thanks for the explanation. I have seen the same error also when deploying with the limited AWS policy, e.g. read only policy.

```
Command sam failed with exit code 1 signal null
Error: Unable to upload artifact src/ referenced by CodeUri parameter of ChimeSdkIndexLambda resource.
An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

From [the AWS CLI Configuration documentation](https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#id1):
> Credentials from environment variables have precedence over credentials from the shared credentials and AWS CLI config file.

In [the Chime SDK deployment script](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/deploy.js), I can't find any command referencing specific credentials, but the script just follows the AWS CLI's precedence rule.
1. Environment variables
2. The shared credentials file
3. The AWS CLI config file
