### ISSUE TITLE
ForbiddenException when accessing from Vercel Serverless Environment 

### ISSUE THREAD

**Issue by jtlacci** [aws/amazon-chime-sdk-js#647]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

```
ForbiddenException: AWS authorization failed
    at Object.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:690:12) {
  code: 'ForbiddenException',
  time: 2020-09-01T22:18:29.722Z,
  requestId: 'e56cf96c-debd-4a39-8986-e742ba55fefb',
  statusCode: 403,
  retryable: false,
  retryDelay: 15.025896480939505
}
```

**Describe the bug**

This is the code I'm using to instantiate the Chime SDK:
```js
const AWS = require('aws-sdk');

AWS.config = new AWS.Config();
AWS.config.accessKeyId = process.env.AWS_ACCESSKEYID;
AWS.config.secretAccessKey = process.env.AWS_SECRETACCESSKEY;

// You must use "us-east-1" as the region for Chime API and set the endpoint.
const chime = new AWS.Chime({ region: 'us-east-1' });
chime.endpoint = new AWS.Endpoint('https://service.chime.aws.amazon.com/console');
```
This code works fine locally when running in a dockerized Next.js instance, I am able to create/join meetings.
However, when I deploy my code to Vercel, it throws a ForbiddenException. 

**Screenshots**
These are the current IAM Policies I have in place
![image](https://user-images.githubusercontent.com/23225162/91912492-458c9980-ec81-11ea-9f38-da6d1a64a125.png)

**Comment by jtlacci** [comment]
changing the code to this fixed it, not sure why it was inconsistent 

```js
// You must use "us-east-1" as the region for Chime API and set the endpoint.
const chime = new AWS.Chime({
  region: 'us-east-1',
  accessKeyId: process.env.AWS_ACCESSKEYID,
  secretAccessKey: process.env.AWS_SECRETACCESSKEY,
});
chime.endpoint = new AWS.Endpoint('https://service.chime.aws.amazon.com/console');
```
