### ISSUE TITLE
Random test failure in DefaultJPEGDecoderComponentFactory tests

### ISSUE THREAD

**Issue by rnewman** [aws/amazon-chime-sdk-js#773]
I routinely see this spurious test failure pop up at random times. Most test runs will complete successfully.

```
  1) DefaultJPEGDecoderComponentFactory
       controller
         creates a controller and then frees it:
     Uncaught ReferenceError: WebSocket is not defined
      at DefaultWebSocketAdapter.readyState (src/websocketadapter/DefaultWebSocketAdapter.ts:4:2213)
      at DefaultSignalingClient.ready (src/signalingclient/DefaultSignalingClient.ts:9:2990)
      at DefaultSignalingClient.sendMessage (src/signalingclient/DefaultSignalingClient.ts:9:5370)
      at DefaultSignalingClient.sendClientMetrics (src/signalingclient/DefaultSignalingClient.ts:9:1531)
      at DefaultStatsCollector.sendClientMetricProtobuf (src/statscollector/DefaultStatsCollector.ts:16:3314)
      at DefaultStatsCollector.handleRawMetricReports (src/statscollector/DefaultStatsCollector.ts:20:4725)
      at ~/sdk/src/statscollector/DefaultStatsCollector.ts:25:490
      at MockPeerConnection.DOMMockBuilder.GlobalAny.RTCPeerConnection.MockPeerConnection.getStats (test/dommock/DOMMockBuilder.ts:729:13)
      at DefaultStatsCollector.getStatsWrapper (src/statscollector/DefaultStatsCollector.ts:23:45)
      at Timeout._onTimeout (src/statscollector/DefaultStatsCollector.ts:12:1060)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) DefaultJPEGDecoderComponentFactory
       controller
         creates a controller and then frees it:
     Error: done() called multiple times in test <DefaultJPEGDecoderComponentFactory controller creates a controller and then frees it> of file ~/sdk/test/jpegdecoder/DefaultJPEGDecoderComponentFactory.test.ts
  ```

**Comment by anuranduttaroy** [comment]
`DefaultJPEGDecoderComponentFactory` which was related to legacy screen-share is removed as part of [amazon-chime-sdk-js release 2.0.0](https://www.npmjs.com/package/amazon-chime-sdk-js/v/2.0.0). This should not be an issue anymore.
