### ISSUE TITLE
Cannot run browser demo - "not a git repository" error

### ISSUE THREAD

**Issue by k-ahn** [aws/amazon-chime-sdk-js#799]
I've downloaded the entire repository, navigated to `demos/browser`, initiated `npm run start` as advised then i get this error:

```
C:\Apps\chimeAppDemo\amazon-chime-sdk-js-master\node_modules\git-describe\lib\git-describe.js:81
        throw err;
        ^

Error: Git returned with status 128: fatal: not a git repository (or any of the parent directories): .git
    at handleProcessResult (C:\Apps\chimeAppDemo\amazon-chime-sdk-js-master\node_modules\git-describe\lib\git-describe.js:76:19)        
    at wrapper (C:\Apps\chimeAppDemo\amazon-chime-sdk-js-master\node_modules\lodash\lodash.js:5213:19)
    at gitDescribe (C:\Apps\chimeAppDemo\amazon-chime-sdk-js-master\node_modules\git-describe\lib\git-describe.js:46:16)
    at wrapper (C:\Apps\chimeAppDemo\amazon-chime-sdk-js-master\node_modules\lodash\lodash.js:5213:19)
    at Object.<anonymous> (C:\Apps\chimeAppDemo\amazon-chime-sdk-js-master\script\generate-version.js:7:36)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-chime-sdk-js@1.20.1 build: `npm install && node script/barrelize.js && node script/generate-version.js && npm run tsc:src && npm run tsc:guides && npm run copy`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amazon-chime-sdk-js@1.20.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kevin\AppData\Roaming\npm-cache\_logs\2020-10-20T23_59_42_547Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-chime-sdk-js-demos@0.1.0 deps: `cd ../.. && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 deps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kevin\AppData\Roaming\npm-cache\_logs\2020-10-20T23_59_42_597Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-chime-sdk-js-demos@0.1.0 start: `npm run deps && npm install && npm install aws-sdk && npm run start:fast`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kevin\AppData\Roaming\npm-cache\_logs\2020-10-20T23_59_42_682Z-debug.log

```

**Comment by devalevenkatesh** [comment]
Hi @k-ahn,

I tried to clone the repo and run the demo. It ran fine for me. I took below steps:
1. Open terminal and create directory where you wish to clone the `amazon-chime-sdk-js` git repository.
2. Change into this newly created directory.
2. Run `git clone https://github.com/aws/amazon-chime-sdk-js.git`
3. Now change directory to the cloned repo: `cd amazon-chime-sdk-js`
3. Now change directory to demo/browser: `cd demos/browser`
4. Now run the app: `npm run start`

Please let me know what steps you followed, and if you are running into error with above steps again?

Please check this [README](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser#browser-meeting) to run the demo meeting app.

**Comment by richnew10** [comment]
The build process will not complete in a plain copy of the repo, including the one you get using "Download ZIP" in the GitHub UI; it needs to be a Git clone in order to determine accurate version information.

Judging by the path in your report, you used "Download ZIP". Please try using GitHub Desktop or another Git client to get a copy of the repository.

**Comment by k-ahn** [comment]
I did Download Zip. Running git clone https://github.com/aws/amazon-chime-sdk-js.git worked

Thanks!
