### ISSUE TITLE
[TypeError] e.calculateMediaStreamConstraints(src/devicecontroller/DefaultDeviceController) errorCannot set property 'echoCancellation' of undefined

### ISSUE THREAD

**Issue by lhong375** [aws/amazon-chime-sdk-js#851]
This is reported by Sentry from our app (backyard.co)

**Timeline**
Outline the main actions the user performed and when:
dozen every day starting Nov 6.

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**

reported by Sentry.  When the error happens, looks like the user failed to grant permissions. I know the type of devices (where we call .echoCancellation on) is either null or string. still somehow we end up with undefined ? we should probably guard against it as well.

*stack trace*
TypeError: Cannot set property 'echoCancellation' of undefined
  at e.calculateMediaStreamConstraints(../../../src/devicecontroller/DefaultDeviceController.ts:868:24)
  at e.<anonymous>(../../../src/devicecontroller/DefaultDeviceController.ts:662:69)
  at ? (2.9e8bd285.chunk.js:8:1)
  at Object.next(2.9e8bd285.chunk.js:8:1)
  at ? (2.9e8bd285.chunk.js:8:1)
  at new Promise(<anonymous>)
  at r(2.9e8bd285.chunk.js:8:1)
  at e.chooseInputDevice(2.9e8bd285.chunk.js:636:5)
  at e.<anonymous>(../../../src/devicecontroller/DefaultDeviceController.ts:102:31)
  at ? (2.9e8bd285.chunk.js:8:1)
  at Object.next(2.9e8bd285.chunk.js:8:1)
  at ? (2.9e8bd285.chunk.js:8:1)
  at new Promise(<anonymous>)
  at r(2.9e8bd285.chunk.js:8:1)
  at e.chooseAudioInputDevice(2.9e8bd285.chunk.js:101:32)
  at chooseAudioInputDevice(../../../src/audiovideofacade/DefaultAudioVideoFacade.ts:329:42)
  at call(../../core/video/src/chime/ChimeRoom.ts:131:61)
  at tryCatch(../../node_modules/regenerator-runtime/runtime.js:63:40)
  at _invoke(../../node_modules/regenerator-runtime/runtime.js:293:22)
  at key(../../node_modules/regenerator-runtime/runtime.js:118:21)
  at asyncGeneratorStep(../../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:20)
  at _next(../../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:9)
  at ? (../../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:32:7)
  at new Promise(<anonymous>)
  at e.<anonymous>(../../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:21:12)
  at setAudioInput(../../core/video/src/chime/ChimeRoom.ts:16:1)
  at call(../../core/video/src/chime/ChimeVideoProvider.ts:182:16)
  at tryCatch(../../node_modules/regenerator-runtime/runtime.js:63:40)
  at _invoke(../../node_modules/regenerator-runtime/runtime.js:293:22)
  at key(../../node_modules/regenerator-runtime/runtime.js:118:21)
  at asyncGeneratorStep(../../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:3:20)
  at _next(../../node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js:25:9)

**Screenshots**
I dig into the DefaultDeviceController.ts itself a bit, this could be the path cause it.

<img width="757" alt="Screen Shot 2020-11-08 at 3 43 18 PM" src="https://user-images.githubusercontent.com/3734721/98488393-bc906200-21dd-11eb-8996-d4a6544d924d.png">

<img width="790" alt="Screen Shot 2020-11-08 at 3 42 54 PM" src="https://user-images.githubusercontent.com/3734721/98488397-c2864300-21dd-11eb-9266-e380e1ba333b.png">

<img width="838" alt="Screen Shot 2020-11-08 at 3 41 16 PM" src="https://user-images.githubusercontent.com/3734721/98488400-c619ca00-21dd-11eb-9c10-94637c749220.png">

<img width="817" alt="Screen Shot 2020-11-08 at 3 48 42 PM" src="https://user-images.githubusercontent.com/3734721/98488412-dc278a80-21dd-11eb-8875-728fa4a08790.png">
 

*couple screenshot of the Sentry report*

<img width="1378" alt="Screen Shot 2020-11-08 at 4 12 22 PM" src="https://user-images.githubusercontent.com/3734721/98488473-2d377e80-21de-11eb-9a4c-c70b2b008ffa.png">

<img width="1349" alt="Screen Shot 2020-11-08 at 4 12 35 PM" src="https://user-images.githubusercontent.com/3734721/98488476-31fc3280-21de-11eb-9130-8ba6e7282add.png">

* its breadscrumbs *

<img width="1092" alt="Screen Shot 2020-11-08 at 4 19 49 PM" src="https://user-images.githubusercontent.com/3734721/98488487-4e986a80-21de-11eb-88fd-d35b52e05275.png">

<img width="1074" alt="Screen Shot 2020-11-08 at 4 19 57 PM" src="https://user-images.githubusercontent.com/3734721/98488492-548e4b80-21de-11eb-8dc4-e124af57dcc5.png">

<img width="1051" alt="Screen Shot 2020-11-08 at 4 20 04 PM" src="https://user-images.githubusercontent.com/3734721/98488495-59eb9600-21de-11eb-8b06-002de74927e0.png">

**Platform**
according to Sentry:
 - OS: Windows 10 (90%)
 - Browser: mostly Chrome
 - Browser Version: 86
 - Amazon Chime SDK GitHub Commit:

**Comment by anuranduttaroy** [comment]
Looks similar to https://github.com/aws/amazon-chime-sdk-js/issues/755

**Comment by ltrung** [comment]
Thanks for pointing this out. You should no longer see that error in Amazon Chime SDK JS v2.0+: I know the type of devices (where we call .echoCancellation on) is either null or string. still somehow we end up with undefined.
With that said, I think the only way this would happen is if you pass undefined into chooseAudioInputDevice so I think we can do some defensive coding there and quit early.

**Comment by ltrung** [comment]
Fixed in #900
